### ISSUE TITLE
Predefined Replies Missing

### ISSUE THREAD

**Issue by Jeremia-h** [LukasWieditz/EditorManager#3]
Installing this addon side-by-side with [Brivium's Support Ticket System](https://brivium.com/resources/brivium-support-ticket-system.98/) seems to block their ticket system's predefined replies. I'm not sure if it's something to do with the toolbar. Works fine when I disable this addon.

**Comment by LukasWieditz** [comment]
They'll have to add support for the Editor Manager. I'm unfortunately not interested in building support for their add-ons.
