### ISSUE TITLE
Moderator only BB Code

### ISSUE THREAD

**Issue by Nirjonadda** [LukasWieditz/EditorManager#4]
Please add Moderator only BB Code with option "Moderator only bb-code"

Moderator only bb-code
```
    alert
    warning
    stop
    information
```

![alert](https://user-images.githubusercontent.com/6899856/55157500-d1c99180-515c-11e9-95f6-1465631be945.png)

**Comment by LukasWieditz** [comment]
You can create a custom BB code and use user criteria to control this.

**Comment by Nirjonadda** [comment]
But I have not the code and CSS for style. If you add this BB Code in your add-on then that will be great.
