### ISSUE TITLE
Add-on Validator error

### ISSUE THREAD

**Issue by Nirjonadda** [LukasWieditz/EditorManager#9]
Getting error with [Add-on Validator](https://xenforo.com/community/resources/al-add-on-validator.7640/) addon.

`Editor & BB Code Manager - class extension does not use XFCP prefix: KL\EditorManager\XF\BbCode\RuleSet
`

![ScreenShot00013](https://user-images.githubusercontent.com/6899856/94848745-b8c23080-0424-11eb-9990-730e6fb888ea.png)

**Comment by LukasWieditz** [comment]
I don't know what this is, but the class extension is correct as you can see here:
https://github.com/LukasWieditz/EditorManager/blob/master/XF/BbCode/RuleSet.php
